inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0

Metrics/BlockLength:
  Exclude:
    - Guardfile
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - Guardfile
    - spec/**/*
